create table shr
(name varchar,
middle_name varchar,
surname varchar,
gender varchar,
age bigint);
select * from shr
insert into shr(name,middle_name,surname,gender,age)values('riya','harish','tambekar','female','22'),
('riya', 'harish', 'tambekar', 'female', '22'),  
('priya', 'rohan', 'sharma', 'female', '25'),  
('sneha', 'amit', 'verma', 'female', '23'),  
('pooja', 'vikram', 'joshi', 'female', '24'),  
('anjali', 'rahul', 'patil', 'female', '26'),  
('jyoti', 'suresh', 'yadav', 'female', '22'),  
('simran', 'arjun', 'mishra', 'female', '27'),  
('neha', 'varun', 'shukla', 'female', '21'),  
('tanya', 'manish', 'thakur', 'female', '25'),  
('kavita', 'deepak', 'nayar', 'female', '23'),  
('meera', 'ashok', 'rai', 'female', '24'),  
('nidhi', 'sachin', 'goyal', 'female', '22'),  
('rekha', 'ravi', 'kapoor', 'female', '26'),  
('divya', 'sandeep', 'bansal', 'female', '28'),  
('rahul', 'deepak', 'sharma', 'male', '24'),  
('vikram', 'arjun', 'singh', 'male', '27'),  
('suresh', 'manoj', 'mishra', 'male', '30'),  
('varun', 'chetan', 'deshmukh', 'male', '26'),  
('rakesh', 'naveen', 'kulkarni', 'male', '28'),  
('harsh', 'rohit', 'pawar', 'male', '22'),  
('kunal', 'gautam', 'tripathi', 'male', '29');  
insert into shr (name,middle_name,surname,gender)values('akash','surendra','wath','male'),
('rohit', 'suresh', 'sharma', 'male'),  
('vikram', 'manoj', 'patil', 'male'),  
('sachin', 'arjun', 'mishra', 'male'),  
('varun', 'chetan', 'deshmukh', 'male'),  
('rakesh', 'naveen', 'kulkarni', 'male'),  
('harsh', 'rohit', 'pawar', 'male'),  
('kunal', 'gautam', 'tripathi', 'male'),  
('amit', 'deepak', 'shinde', 'male'),  
('sandeep', 'vijay', 'bhatt', 'male'),  
('arjun', 'rahul', 'goyal', 'male'),  
('manish', 'ashok', 'rai', 'male'),  
('naveen', 'ravi', 'kapoor', 'male'),  
('deepak', 'sachin', 'bansal', 'male'),  
('rahul', 'vikram', 'joshi', 'male'),  
('chetan', 'suresh', 'yadav', 'male'),  
('gautam', 'tarun', 'verma', 'male'),  
('ashish', 'pankaj', 'shukla', 'male');  

